export function createTestRequest() {
  return {
    request_id: "request-342",
    requested_mode: "new_season" as const,
    requested_modifiers: [],
    goals: [{
      race_name: "西安马拉松",
      location: "西安",
      distance: "FM" as const,
      race_date: "2026-10-18",
      target_time: "2:50:00",
      finish_only: false,
      priority: "A" as const,
    }],
    availability: {
      weekly_run_days_max: 6,
      available_training_windows: [
        { day: "monday" as const, start_time: "06:00", end_time: "08:00" },
        { day: "tuesday" as const, start_time: "06:00", end_time: "08:00" },
        { day: "wednesday" as const, start_time: "06:00", end_time: "08:00" },
        { day: "thursday" as const, start_time: "06:00", end_time: "08:00" },
        { day: "friday" as const, start_time: "06:00", end_time: "08:00" },
        { day: "saturday" as const, start_time: "06:00", end_time: "09:00" },
      ],
      unavailable_days: ["sunday" as const],
      max_session_duration_min: 180,
      allows_double_sessions: false,
      preferred_long_run_day: "saturday" as const,
      strength_sessions_per_week: 2,
      strength_available_days: ["monday" as const, "thursday" as const],
    },
    injury_declarations: [],
    environment_constraints: [],
    travel_constraints: [],
    preferences: [],
    prohibited_arrangements: [],
    active_plan_action: "none" as const,
    user_confirmations: {
      intake_complete: true as const,
      goals_confirmed: true as const,
      availability_confirmed: true as const,
      injury_history_confirmed: true as const,
      constraints_confirmed: true as const,
    },
  };
}

export function createTestMasterPlan() {
  return {
    status: "draft" as const,
    goal: {
      race_name: "西安马拉松",
      distance: "FM" as const,
      race_date: "2026-10-18",
      target_time: "2:50:00",
      timezone: "Asia/Shanghai" as const,
      location: "西安",
    },
    start_date: "2026-08-10",
    end_date: "2026-08-16",
    total_weeks: 1,
    phases: [{
      name: "基础期" as const,
      start_date: "2026-08-10",
      end_date: "2026-08-16",
      focus: "建立赛季起点",
      weekly_distance_km_low: 70,
      weekly_distance_km_high: 80,
      key_session_types: ["long_run"],
      milestones: [],
      key_workouts: "周末长跑",
      monitoring_triggers: ["疼痛加重时降量"],
      coach_note: "保持恢复",
      strength: { sessions_per_week: 2, focus: "核心和下肢耐力", timing: "轻松跑后" },
      recovery: { focus: "睡眠和补给", sleep_target_hours: "7-9", adjustment_trigger: "疼痛或睡眠恶化" },
      is_completed: false,
      summary: null,
    }],
    weeks: [{
      week_index: 1,
      week_start: "2026-08-10",
      phase_name: "基础期" as const,
      target_weekly_km_low: 70,
      target_weekly_km_high: 80,
      key_sessions: [{
        type: "long_run" as const,
        distance_km: 24,
        duration_min: null,
        intensity: "easy",
        purpose: "建立耐力",
      }],
      is_recovery_week: false,
    }],
    training_principles: ["循序渐进"],
    generated_by: "coach_agent" as const,
    version: 1 as const,
    created_at: "2026-08-10T00:00:00Z",
    updated_at: "2026-08-10T00:00:00Z",
  };
}
