/// Snapshot of an available app update.
class UpdateInfo {
  const UpdateInfo({
    required this.tagName,
    required this.versionName,
    required this.apkUrl,
    required this.apkSize,
    this.releaseNotes,
  });

  /// e.g. ``mobile-v2026.5.2``
  final String tagName;

  /// Parsed version, e.g. ``2026.5.2`` (no ``mobile-v`` prefix).
  final String versionName;

  /// Direct download URL of the signed APK asset.
  final String apkUrl;

  /// Size in bytes — used for the progress bar denominator and to give the
  /// user a "how big is this" line in the dialog.
  final int apkSize;

  /// Markdown-formatted release notes (auto-generated by GitHub Releases).
  final String? releaseNotes;
}
