// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/users/me/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the current user's profile, onboarding state and features",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.profileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Persists the five onboarding core fields, marks profile_ready, and best-effort mirrors the display name to the auth-service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Save the current user's basic profile",
                "parameters": [
                    {
                        "description": "Profile core fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.profileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/me/watch": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the connected watch's status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.watchInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes the stored watch credential and marks watch_ready=false. Synced activity/health data is retained. Returns 400 when no watch is bound.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Disconnect the current user's watch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.disconnectWatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/me/watch/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the watch account, persists credentials, and marks watch_ready. Provider is selected in the body; region applies to Garmin. Triggers no sync.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Connect a watch provider (COROS/Garmin)",
                "parameters": [
                    {
                        "description": "Watch provider credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.watchLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.watchLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/{uid}/pipelines": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists the pipeline runs for a user (the subject whose data they operate on), most recent first. A user caller may only list their own runs (uid must equal their JWT sub); an internal caller may list any uid.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "List a user's pipeline runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id (the subject; JWT sub)",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userPipelinesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/{user}/activities": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a filtered, paginated activity page (newest first) plus run-distance/duration/count summaries for every Shanghai month on the page. A user caller may only list their own activities; an internal caller may list any user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "List a user's activities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id (JWT sub)",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size 1–200 (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact sport_name filter",
                        "name": "sport",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "run | strength",
                        "name": "sport_category",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum distance in km",
                        "name": "min_distance_km",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Shanghai YYYY-MM-DD lower bound",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Shanghai YYYY-MM-DD upper bound",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.activitiesListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/{user}/activities/{labelId}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assembles the activity, objective training load, laps, strength segments, watch-reported zones, and (with ?include=timeseries) the downsampled timeseries. A user caller may only read their own activities; an internal caller may read any user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get one activity's detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id (JWT sub)",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity label id",
                        "name": "labelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma list; pass 'timeseries' to inline the series",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.activityDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/{user}/sync": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts the data-sync pipeline for the user and returns immediately (202) with a run id; poll GET /pipelines/{run_id} for completion. The pipeline syncs watch data and then computes derived metrics (training load, PMC, personal bests). Mode picks the pipeline: \"incremental\" (default) syncs only new activities and computes only those; \"full\" re-syncs history, recomputes the athlete baseline, and does a full compute (new-user onboarding). This is the async Go replacement for the Python POST /api/{user}/sync. A user caller may only sync their own id (path {user} must equal their JWT sub); an internal caller may sync any user (path {user} must be a UUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Trigger a watch-data sync (+ compute) for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id (JWT sub, or any user UUID for internal callers)",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Optional sync options; omitted mode defaults to incremental",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.syncRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Started",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Returns every job type the system supports (hardcoded in the catalog), each with its input JSON schema and an example input. Static system metadata; no auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List supported job types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.jobCatalogResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a job and publishes it to the worker. Internal callers may target any user and any cataloged job type; user callers may only create user-initiable types and the subject user is derived from their token. Supply an Idempotency-Key header to make retries safe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Enqueue an async job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deduplicates creation; a repeat key returns the existing job (200)",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Job to enqueue",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing job returned for a repeated Idempotency-Key",
                        "schema": {
                            "$ref": "#/definitions/api.enqueueJobResponse"
                        }
                    },
                    "202": {
                        "description": "Enqueued",
                        "schema": {
                            "$ref": "#/definitions/api.enqueueJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{job_id}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get a job's status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job id",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.jobStateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/pipelines": {
            "get": {
                "description": "Returns every pipeline the system supports (hardcoded in the catalog), each with its ordered steps, input JSON schema and an example input. Static system metadata; no auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List supported pipelines",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.pipelineCatalogResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts a named pipeline (a linear sequence of jobs). The pipeline name is supplied in the request body. Internal callers may start any cataloged pipeline for any user; user callers may only start user-initiable pipelines for themselves. Supply an Idempotency-Key header to make retries safe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Start a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deduplicates creation; a repeat key returns the existing run (200)",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Pipeline name (required) and optional subject user/input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing run returned for a repeated Idempotency-Key",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineResponse"
                        }
                    },
                    "202": {
                        "description": "Started",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/pipelines/{run_id}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Get a pipeline run's status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run id",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.runStateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.JobCatalogEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "example_input": {
                    "type": "object"
                },
                "input_schema": {
                    "type": "object"
                },
                "type": {
                    "type": "string",
                    "example": "watch_sync"
                },
                "user_initiable": {
                    "type": "boolean"
                }
            }
        },
        "api.PipelineCatalogEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "example_input": {
                    "type": "object"
                },
                "input_schema": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "onboarding"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PipelineStepInfo"
                    }
                },
                "user_initiable": {
                    "type": "boolean"
                }
            }
        },
        "api.PipelineStepInfo": {
            "type": "object",
            "properties": {
                "job_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.activitiesListResponse": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.activityListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "monthly_summaries": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/api.monthlySummaryDTO"
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.activityDetailDTO": {
            "type": "object",
            "properties": {
                "aerobic_effect": {
                    "type": "number"
                },
                "anaerobic_effect": {
                    "type": "number"
                },
                "ascent_m": {
                    "type": "number"
                },
                "avg_cadence": {
                    "type": "integer"
                },
                "avg_hr": {
                    "type": "integer"
                },
                "avg_pace_s_km": {
                    "type": "number"
                },
                "calories_kcal": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "distance_km": {
                    "type": "number"
                },
                "distance_m": {
                    "type": "number"
                },
                "duration_fmt": {
                    "type": "string"
                },
                "duration_s": {
                    "type": "number"
                },
                "feel_type": {
                    "type": "integer"
                },
                "feels_like": {
                    "type": "number"
                },
                "humidity": {
                    "type": "number"
                },
                "label_id": {
                    "type": "string"
                },
                "max_hr": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pace_fmt": {
                    "type": "string"
                },
                "pauses": {
                    "type": "object"
                },
                "sport_name": {
                    "type": "string"
                },
                "sport_note": {
                    "type": "string"
                },
                "sport_type": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "train_type": {
                    "type": "string"
                },
                "training_load": {
                    "type": "number"
                },
                "vo2max": {
                    "type": "number"
                },
                "wind_speed": {
                    "type": "number"
                }
            }
        },
        "api.activityDetailResponse": {
            "type": "object",
            "properties": {
                "activity": {
                    "$ref": "#/definitions/api.activityDetailDTO"
                },
                "laps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.lapDTO"
                    }
                },
                "linked_scheduled_workout": {
                    "$ref": "#/definitions/api.linkedScheduledWorkoutDTO"
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.segmentDTO"
                    }
                },
                "stride_training_load": {
                    "$ref": "#/definitions/api.strideTrainingLoadDTO"
                },
                "timeseries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.timeseriesDTO"
                    }
                },
                "zones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.zoneDTO"
                    }
                }
            }
        },
        "api.activityListItem": {
            "type": "object",
            "properties": {
                "aerobic_effect": {
                    "type": "number"
                },
                "anaerobic_effect": {
                    "type": "number"
                },
                "ascent_m": {
                    "type": "number"
                },
                "avg_cadence": {
                    "type": "integer"
                },
                "avg_hr": {
                    "type": "integer"
                },
                "avg_pace_s_km": {
                    "type": "number"
                },
                "calories_kcal": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "distance_km": {
                    "type": "number"
                },
                "distance_m": {
                    "type": "number"
                },
                "duration_fmt": {
                    "type": "string"
                },
                "duration_s": {
                    "type": "number"
                },
                "feels_like": {
                    "type": "number"
                },
                "humidity": {
                    "type": "number"
                },
                "label_id": {
                    "type": "string"
                },
                "max_hr": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pace_fmt": {
                    "type": "string"
                },
                "route_thumb": {
                    "type": "object"
                },
                "sport_name": {
                    "type": "string"
                },
                "sport_type": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "train_type": {
                    "type": "string"
                },
                "training_load": {
                    "type": "number"
                },
                "vo2max": {
                    "type": "number"
                },
                "wind_speed": {
                    "type": "number"
                }
            }
        },
        "api.createJobRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "input": {
                    "type": "object"
                },
                "type": {
                    "type": "string",
                    "example": "watch_sync"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.disconnectWatchResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "api.enqueueJobResponse": {
            "type": "object",
            "properties": {
                "deduplicated": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.featureFlags": {
            "type": "object",
            "properties": {
                "coach_agent_weekly_plan": {
                    "type": "boolean"
                },
                "coach_chat": {
                    "type": "boolean"
                },
                "coach_chat_debug": {
                    "type": "boolean"
                },
                "coach_chat_max_message_chars": {
                    "type": "integer"
                },
                "sync_data_at_onboarding": {
                    "type": "boolean"
                }
            }
        },
        "api.jobCatalogResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.JobCatalogEntry"
                    }
                }
            }
        },
        "api.jobStateResponse": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "progress_pct": {
                    "type": "integer"
                },
                "result_json": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.lapDTO": {
            "type": "object",
            "properties": {
                "adjusted_pace": {
                    "type": "number"
                },
                "ascent_m": {
                    "type": "number"
                },
                "avg_cadence": {
                    "type": "integer"
                },
                "avg_hr": {
                    "type": "integer"
                },
                "avg_pace": {
                    "type": "number"
                },
                "avg_power": {
                    "type": "integer"
                },
                "descent_m": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "distance_m": {
                    "type": "number"
                },
                "duration_fmt": {
                    "type": "string"
                },
                "duration_s": {
                    "type": "number"
                },
                "lap_index": {
                    "type": "integer"
                },
                "lap_type": {
                    "type": "string"
                },
                "max_hr": {
                    "type": "integer"
                },
                "pace_fmt": {
                    "type": "string"
                }
            }
        },
        "api.linkedScheduledWorkoutDTO": {
            "type": "object",
            "properties": {
                "abandoned_by_promote_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "api.monthlySummaryDTO": {
            "type": "object",
            "properties": {
                "activity_count": {
                    "type": "integer"
                },
                "duration_s": {
                    "type": "integer"
                },
                "total_run_km": {
                    "type": "number"
                }
            }
        },
        "api.onboardingState": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "profile_ready": {
                    "type": "boolean"
                },
                "watch_ready": {
                    "type": "boolean"
                }
            }
        },
        "api.pipelineCatalogResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PipelineCatalogEntry"
                    }
                }
            }
        },
        "api.pipelineStepResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.profileCore": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "height_cm": {
                    "type": "number"
                },
                "sex": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "api.profileInput": {
            "type": "object",
            "required": [
                "display_name",
                "dob",
                "height_cm",
                "sex",
                "weight_kg"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "height_cm": {
                    "type": "number"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other"
                    ]
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "api.profileResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/api.featureFlags"
                },
                "id": {
                    "type": "string"
                },
                "onboarding": {
                    "$ref": "#/definitions/api.onboardingState"
                },
                "profile": {
                    "$ref": "#/definitions/api.profileCore"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "api.runStateResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_step": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                },
                "pipeline_name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.pipelineStepResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.segmentDTO": {
            "type": "object",
            "properties": {
                "adjusted_pace": {
                    "type": "number"
                },
                "ascent_m": {
                    "type": "number"
                },
                "avg_cadence": {
                    "type": "integer"
                },
                "avg_hr": {
                    "type": "integer"
                },
                "avg_pace": {
                    "type": "number"
                },
                "avg_power": {
                    "type": "integer"
                },
                "descent_m": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "distance_m": {
                    "type": "number"
                },
                "duration_fmt": {
                    "type": "string"
                },
                "duration_s": {
                    "type": "number"
                },
                "lap_index": {
                    "type": "integer"
                },
                "lap_type": {
                    "type": "string"
                },
                "max_hr": {
                    "type": "integer"
                },
                "mode": {
                    "type": "integer"
                },
                "pace_fmt": {
                    "type": "string"
                },
                "seg_name": {
                    "type": "string"
                }
            }
        },
        "api.startPipelineRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "onboarding"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.startPipelineResponse": {
            "type": "object",
            "properties": {
                "deduplicated": {
                    "type": "boolean"
                },
                "pipeline_name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                }
            }
        },
        "api.strideTrainingLoadDTO": {
            "type": "object",
            "properties": {
                "activity_date": {
                    "type": "string"
                },
                "algorithm_version": {
                    "type": "integer"
                },
                "calibration_id": {
                    "type": "integer"
                },
                "cardio_coverage": {
                    "type": "number"
                },
                "cardio_load_raw": {
                    "type": "number"
                },
                "cardio_tss": {
                    "type": "number"
                },
                "coverage_status": {
                    "type": "string"
                },
                "excluded_from_pmc": {
                    "type": "boolean"
                },
                "external_coverage": {
                    "type": "number"
                },
                "external_tss": {
                    "type": "number"
                },
                "high_intensity_coverage": {
                    "type": "number"
                },
                "high_intensity_tss": {
                    "type": "number"
                },
                "label_id": {
                    "type": "string"
                },
                "load_confidence": {
                    "type": "string"
                },
                "mechanical_load": {
                    "type": "number"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_class": {
                    "type": "string"
                },
                "sport": {
                    "type": "string"
                },
                "subjective_internal_load": {
                    "type": "number"
                },
                "training_dose": {
                    "type": "number"
                },
                "training_dose_source": {
                    "type": "string"
                }
            }
        },
        "api.syncRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "enum": [
                        "all",
                        "activities",
                        "health"
                    ],
                    "example": "all"
                },
                "limit": {
                    "type": "integer",
                    "example": 0
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "full",
                        "incremental"
                    ],
                    "example": "incremental"
                }
            }
        },
        "api.timeseriesDTO": {
            "type": "object",
            "properties": {
                "adjusted_pace": {
                    "type": "number"
                },
                "altitude": {
                    "type": "number"
                },
                "cadence": {
                    "type": "integer"
                },
                "distance": {
                    "type": "number"
                },
                "gps_lat": {
                    "type": "number"
                },
                "gps_lon": {
                    "type": "number"
                },
                "heart_rate": {
                    "type": "integer"
                },
                "power": {
                    "type": "integer"
                },
                "speed": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "api.userPipelinesResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.runStateResponse"
                    }
                }
            }
        },
        "api.validationDetailItem": {
            "type": "object",
            "properties": {
                "loc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "api.validationErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.validationDetailItem"
                    }
                }
            }
        },
        "api.watchInfoResponse": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_sync_at": {
                    "type": "string"
                },
                "logged_in": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "provider_display_name": {
                    "type": "string"
                }
            }
        },
        "api.watchLoginInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "provider"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "coros",
                        "garmin"
                    ]
                },
                "region": {
                    "type": "string",
                    "enum": [
                        "cn",
                        "global"
                    ]
                }
            }
        },
        "api.watchLoginResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "region": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.zoneDTO": {
            "type": "object",
            "properties": {
                "duration_s": {
                    "type": "integer"
                },
                "percent": {
                    "type": "number"
                },
                "range_max": {
                    "type": "number"
                },
                "range_min": {
                    "type": "number"
                },
                "range_unit": {
                    "type": "string"
                },
                "zone_index": {
                    "type": "integer"
                },
                "zone_type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003cJWT\u003e\" for end-user callers (RS256).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "InternalToken": {
            "description": "Shared secret for server-to-server callers.",
            "type": "apiKey",
            "name": "X-Internal-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "STRIDE API",
	Description:      "HTTP API fronting the STRIDE worker: create and track async jobs and pipeline runs, and manage user profile, onboarding, and watch-provider login.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
