// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/users/me/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the current user's profile, onboarding state and features",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.profileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Persists the five onboarding core fields, marks profile_ready, and best-effort mirrors the display name to the auth-service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Save the current user's basic profile",
                "parameters": [
                    {
                        "description": "Profile core fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.profileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/me/watch": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the connected watch's status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.watchInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes the stored watch credential and marks watch_ready=false. Synced activity/health data is retained. Returns 400 when no watch is bound.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Disconnect the current user's watch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.disconnectWatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/me/watch/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the watch account, persists credentials, and marks watch_ready. Provider is selected in the body; region applies to Garmin. Triggers no sync.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Connect a watch provider (COROS/Garmin)",
                "parameters": [
                    {
                        "description": "Watch provider credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.watchLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.watchLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/{uid}/pipelines": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists the pipeline runs for a user (the subject whose data they operate on), most recent first. A user caller may only list their own runs (uid must equal their JWT sub); an internal caller may list any uid.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "List a user's pipeline runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id (the subject; JWT sub)",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userPipelinesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Returns every job type the system supports (hardcoded in the catalog), each with its input JSON schema and an example input. Static system metadata; no auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List supported job types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.jobCatalogResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a job and publishes it to the worker. Internal callers may target any user and any cataloged job type; user callers may only create user-initiable types and the subject user is derived from their token. Supply an Idempotency-Key header to make retries safe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Enqueue an async job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deduplicates creation; a repeat key returns the existing job (200)",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Job to enqueue",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing job returned for a repeated Idempotency-Key",
                        "schema": {
                            "$ref": "#/definitions/api.enqueueJobResponse"
                        }
                    },
                    "202": {
                        "description": "Enqueued",
                        "schema": {
                            "$ref": "#/definitions/api.enqueueJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{job_id}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get a job's status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job id",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.jobStateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/pipelines": {
            "get": {
                "description": "Returns every pipeline the system supports (hardcoded in the catalog), each with its ordered steps, input JSON schema and an example input. Static system metadata; no auth required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List supported pipelines",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.pipelineCatalogResponse"
                        }
                    }
                }
            }
        },
        "/pipelines/{name}": {
            "post": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts a named pipeline (a linear sequence of jobs). Internal callers may start any cataloged pipeline for any user; user callers may only start user-initiable pipelines for themselves. Supply an Idempotency-Key header to make retries safe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Start a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deduplicates creation; a repeat key returns the existing run (200)",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Optional subject user/input",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing run returned for a repeated Idempotency-Key",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineResponse"
                        }
                    },
                    "202": {
                        "description": "Started",
                        "schema": {
                            "$ref": "#/definitions/api.startPipelineResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/pipelines/{run_id}": {
            "get": {
                "security": [
                    {
                        "InternalToken": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Get a pipeline run's status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run id",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.runStateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.JobCatalogEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "example_input": {
                    "type": "object"
                },
                "input_schema": {
                    "type": "object"
                },
                "type": {
                    "type": "string",
                    "example": "watch_sync"
                },
                "user_initiable": {
                    "type": "boolean"
                }
            }
        },
        "api.PipelineCatalogEntry": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "example_input": {
                    "type": "object"
                },
                "input_schema": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "onboarding"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PipelineStepInfo"
                    }
                },
                "user_initiable": {
                    "type": "boolean"
                }
            }
        },
        "api.PipelineStepInfo": {
            "type": "object",
            "properties": {
                "job_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.createJobRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "input": {
                    "type": "object"
                },
                "type": {
                    "type": "string",
                    "example": "watch_sync"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.disconnectWatchResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "api.enqueueJobResponse": {
            "type": "object",
            "properties": {
                "deduplicated": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.featureFlags": {
            "type": "object",
            "properties": {
                "coach_agent_weekly_plan": {
                    "type": "boolean"
                },
                "coach_chat": {
                    "type": "boolean"
                },
                "coach_chat_debug": {
                    "type": "boolean"
                },
                "coach_chat_max_message_chars": {
                    "type": "integer"
                },
                "sync_data_at_onboarding": {
                    "type": "boolean"
                }
            }
        },
        "api.jobCatalogResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.JobCatalogEntry"
                    }
                }
            }
        },
        "api.jobStateResponse": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "progress_pct": {
                    "type": "integer"
                },
                "result_json": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.onboardingState": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "profile_ready": {
                    "type": "boolean"
                },
                "watch_ready": {
                    "type": "boolean"
                }
            }
        },
        "api.pipelineCatalogResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PipelineCatalogEntry"
                    }
                }
            }
        },
        "api.pipelineStepResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.profileCore": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "height_cm": {
                    "type": "number"
                },
                "sex": {
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "api.profileInput": {
            "type": "object",
            "required": [
                "display_name",
                "dob",
                "height_cm",
                "sex",
                "weight_kg"
            ],
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "height_cm": {
                    "type": "number"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other"
                    ]
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "api.profileResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/api.featureFlags"
                },
                "id": {
                    "type": "string"
                },
                "onboarding": {
                    "$ref": "#/definitions/api.onboardingState"
                },
                "profile": {
                    "$ref": "#/definitions/api.profileCore"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "api.runStateResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_step": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                },
                "pipeline_name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.pipelineStepResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.startPipelineRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.startPipelineResponse": {
            "type": "object",
            "properties": {
                "deduplicated": {
                    "type": "boolean"
                },
                "pipeline_name": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                }
            }
        },
        "api.userPipelinesResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.runStateResponse"
                    }
                }
            }
        },
        "api.validationDetailItem": {
            "type": "object",
            "properties": {
                "loc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "api.validationErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.validationDetailItem"
                    }
                }
            }
        },
        "api.watchInfoResponse": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "device": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_sync_at": {
                    "type": "string"
                },
                "logged_in": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "provider_display_name": {
                    "type": "string"
                }
            }
        },
        "api.watchLoginInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "provider"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "coros",
                        "garmin"
                    ]
                },
                "region": {
                    "type": "string",
                    "enum": [
                        "cn",
                        "global"
                    ]
                }
            }
        },
        "api.watchLoginResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "region": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003cJWT\u003e\" for end-user callers (RS256).",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "InternalToken": {
            "description": "Shared secret for server-to-server callers.",
            "type": "apiKey",
            "name": "X-Internal-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "STRIDE API",
	Description:      "HTTP API fronting the STRIDE worker: create and track async jobs and pipeline runs, and manage user profile, onboarding, and watch-provider login.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
