"""MasterPlan storage — public interface (Tier A).

Pure Protocol over the ``stride_core.master_plan`` domain types. No I/O import.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from stride_core.master_plan import MasterPlan, MasterPlanVersion


@runtime_checkable
class MasterPlanStore(Protocol):
    def save_plan(self, plan: MasterPlan) -> None: ...
    def get_plan(self, user_id: str, plan_id: str) -> MasterPlan | None: ...
    def get_active_plan(self, user_id: str) -> MasterPlan | None: ...
    def list_active_plans(self) -> list[MasterPlan]: ...
    def list_plans(self, user_id: str) -> list[MasterPlan]: ...
    def archive_previous(self, user_id: str, new_plan_id: str) -> None: ...
    def save_version(self, version: MasterPlanVersion) -> None: ...
    def list_versions(self, plan_id: str) -> list[MasterPlanVersion]: ...
    def get_version(
        self, plan_id: str, version_id: str,
    ) -> MasterPlanVersion | None: ...
